
name: Zig CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Zig
        run: |
          curl -L https://ziglang.org/download/0.14.0/zig-linux-x86_64-0.14.0.tar.xz | tar -xJ
          sudo mv zig-linux-x86_64-0.14.0 /usr/local/zig
          sudo ln -s /usr/local/zig/zig /usr/local/bin/zig
      - name: Run Tests
        run: |
          zig build test
